http:
  port: 7000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: 
      - '/auth/*'
      - '/user/*'
  job:
    host: localhost
    paths: 
      - '/job/*'
      - '/candidate/*'
serviceEndpoints:
  auth:
    url: 'http://localhost:7001'
  job:
    url: 'http://localhost:7002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: 'http://localhost:8081'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: auth
  - name: job
    apiEndpoints:
      - job
    policies:
      - cors:
          - action:
              origin: 'http://localhost:8081'
              methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
              allowedHeaders: ['Content-Type', 'Authorization']
      - proxy:
          - action:
              serviceEndpoint: job
